# Generated by Django 5.1.7 on 2025-03-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название тега"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(db_index=True, primary_key=True, serialize=False),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Время добавления"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        verbose_name="Наименование задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(verbose_name="Дедлайн выполнения задачи"),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Отменена"),
                            (2, "Активная"),
                            (3, "Выполнена"),
                            (4, "Просрочена"),
                        ],
                        default=2,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasks",
                        to="tasks.category",
                        verbose_name="Категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
