# Generated by Django 5.1.7 on 2025-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(1, "Активная"), (2, "Выполнена"), (3, "Просрочена")],
                default=1,
                verbose_name="Статус задачи",
            ),
        ),
    ]
