# Generated by Django 5.1.7 on 2025-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Выполнена"),
        ),
    ]
